name: ds
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.3.1
  - attrs=22.1.0
  - blosc=1.21.1
  - boost-cpp=1.78.0
  - branca=0.5.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.9.24
  - cairo=1.16.0
  - cartopy=0.21.0
  - certifi=2022.9.24
  - cffi=1.15.1
  - cfitsio=4.1.0
  - charset-normalizer=2.1.1
  - click=8.1.3
  - click-plugins=1.1.1
  - cligj=0.7.2
  - contextily=1.2.0
  - contourpy=1.0.5
  - cryptography=37.0.1
  - curl=7.85.0
  - cycler=0.11.0
  - expat=2.4.9
  - fiona=1.8.21
  - folium=0.13.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.37.4
  - freetype=2.12.1
  - freexl=1.0.6
  - gdal=3.5.2
  - geographiclib=1.52
  - geopandas=0.11.1
  - geopandas-base=0.11.1
  - geoplot=0.5.1
  - geopy=2.2.0
  - geos=3.11.0
  - geotiff=1.7.1
  - gettext=0.19.8.1
  - giflib=5.2.1
  - hdf4=4.2.15
  - hdf5=1.12.2
  - icu=70.1
  - idna=3.4
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - json-c=0.16
  - kealib=1.4.15
  - kiwisolver=1.4.4
  - krb5=1.19.3
  - lcms2=2.12
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=7.85.0
  - libcxx=14.0.6
  - libdap4=3.20.6
  - libdeflate=1.14
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgdal=3.5.2
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libglib=2.74.0
  - libiconv=1.17
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.8.1
  - libnghttp2=1.47.0
  - libopenblas=0.3.21
  - libpng=1.6.38
  - libpq=14.5
  - librttopo=1.1.0
  - libspatialindex=1.9.3
  - libspatialite=5.0.1
  - libsqlite=3.39.4
  - libssh2=1.10.0
  - libtiff=4.4.0
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxml2=2.10.2
  - libzip=1.9.2
  - libzlib=1.2.12
  - llvm-openmp=14.0.4
  - lz4-c=1.9.3
  - mapclassify=2.4.3
  - markupsafe=2.1.1
  - matplotlib-base=3.6.1
  - mercantile=1.2.1
  - munch=2.5.0
  - munkres=1.1.4
  - ncurses=6.3
  - networkx=2.8.7
  - nspr=4.32
  - nss=3.78
  - numpy=1.23.3
  - openjpeg=2.5.0
  - openssl=3.0.5
  - packaging=21.3
  - pcre=8.45
  - pcre2=10.37
  - pillow=9.2.0
  - pip=22.2.2
  - pixman=0.40.0
  - poppler=22.04.0
  - poppler-data=0.4.11
  - postgresql=14.5
  - proj=9.0.1
  - pthread-stubs=0.4
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyproj=3.4.0
  - pyshp=2.3.1
  - pysocks=1.7.1
  - python=3.10.6
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pytz=2022.4
  - rasterio=1.3.2
  - readline=8.1.2
  - requests=2.28.1
  - rtree=1.0.1
  - scikit-learn=1.1.2
  - scipy=1.9.1
  - seaborn-base=0.12.0
  - setuptools=65.4.1
  - shapely=1.8.5
  - six=1.16.0
  - snappy=1.1.9
  - snuggs=1.4.7
  - sqlite=3.39.4
  - threadpoolctl=3.1.0
  - tiledb=2.11.3
  - tk=8.6.12
  - typing_extensions=4.4.0
  - tzcode=2022e
  - tzdata=2022e
  - unicodedata2=14.0.0
  - wheel=0.37.1
  - xerces-c=3.2.3
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xyzservices=2022.9.0
  - xz=5.2.6
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - pandas==1.5.0
    - urllib3==1.26.12
